import './globals.css'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

import ThemeRegistry from '~/theme/ThemeRegistry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>{children}</body>
      </ThemeRegistry>
    </html>
  )
}
